name: Github Action CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request: # opened, synchronize, reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Set up Gradle 7.6.1
        uses: gradle/gradle-build-action@v1
        with:
          gradle-version: 7.6.1

      - name: Build with Gradle
        run: ./gradlew build
